#ifndef _QX_PMNG_EXPORT_H_
#define _QX_PMNG_EXPORT_H_

#ifdef _BUILDING_QX_PMNG
#define QX_PMNG_DLL_EXPORT QX_DLL_EXPORT_HELPER
#else // _BUILDING_QX_PMNG
#define QX_PMNG_DLL_EXPORT QX_DLL_IMPORT_HELPER
#endif // _BUILDING_QX_PMNG

#ifdef _BUILDING_QX_PMNG
#define QX_REGISTER_HPP_QX_PMNG     QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_QX_PMNG     QX_REGISTER_CPP_EXPORT_DLL
#else // _BUILDING_QX_PMNG
#define QX_REGISTER_HPP_QX_PMNG     QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_QX_PMNG     QX_REGISTER_CPP_IMPORT_DLL
#endif // _BUILDING_QX_PMNG

#endif // _QX_PMNG_EXPORT_H_
